# Generated by Django 5.2.15 on 2026-07-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='site_url',
            field=models.URLField(blank=True, default='', help_text='Адресът на сайта, за който е тикетът', verbose_name='Сайт'),
        ),
    ]
