# Generated by Django 5.2.15 on 2026-07-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_site_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Мани, че почека'), ('normal', 'Кога можеш, баце'), ('high', 'Тичай, че гори!')], default='normal', max_length=20),
        ),
    ]
